# Crowdin configuration file
# https://developer.crowdin.com/configuration-file/

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

# Preserve MDX/Markdown formatting
preserve_hierarchy: true

files:
  # Documentation content
  - source: /src/content/docs/**/*.mdx
    # Translations go to language subfolders (e.g. src/content/docs/en/file.mdx)
    # The %two_letters_code% placeholder ensures we get 'en' instead of 'en-US'
    translation: /src/content/docs/%two_letters_code%/**/%original_file_name%
    # Exclude already translated folders
    ignore:
      - /src/content/docs/en/**/*
      - /src/content/docs/zh/**/*
      - /src/content/docs/ja/**/*
      - /src/content/docs/ko/**/*
